### ISSUE TITLE
3.5.2 IllegalAccessError: io/netty/channel/VoidChannelPromise

### ISSUE THREAD

**Issue by connorliveraise** [vert-x3/vertx-mysql-postgresql-client#115]
vertx 3.5.2 requires a netty version with a public VoidChannelPromise, however com.github.mauricio is stuck depending on netty 4.1.6 which is too old. Please update pom to exclude netty transitive, and manually use a newer netty version.

2018-06-12 21:47:49.538 [WARN ] [vert.x-eventloop-thread-0] DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline.
It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.ChannelPipelineException: io.vertx.core.net.impl.NetClientImpl$1.handlerAdded() has thrown an exception; removed.
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:616) ~[my-vertx-project-1.0.jar:1.0]
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:226) ~[my-vertx-project-1.0.jar:1.0]
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:192) ~[my-vertx-project-1.0.jar:1.0]
        at io.vertx.core.net.impl.NetClientImpl.connected(NetClientImpl.java:257) ~[my-vertx-project-1.0.jar:1.0]
        at io.vertx.core.net.impl.NetClientImpl.lambda$doConnect$7(NetClientImpl.java:212) ~[my-vertx-project-1.0.jar:1.0]
        at io.vertx.core.net.impl.ChannelProvider.lambda$connect$0(ChannelProvider.java:52) ~[my-vertx-project-1.0.jar:1.0]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514) [my-vertx-project-1.0.jar:1.0]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:507) [my-vertx-project-1.0.jar:1.0]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:486) [my-vertx-project-1.0.jar:1.0]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:427) [my-vertx-project-1.0.jar:1.0]
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:111) [my-vertx-project-1.0.jar:1.0]
        at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82) [my-vertx-project-1.0.jar:1.0]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:306) [my-vertx-project-1.0.jar:1.0]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:341) [my-vertx-project-1.0.jar:1.0]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:639) [my-vertx-project-1.0.jar:1.0]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574) [my-vertx-project-1.0.jar:1.0]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488) [my-vertx-project-1.0.jar:1.0]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450) [my-vertx-project-1.0.jar:1.0]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) [my-vertx-project-1.0.jar:1.0]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.IllegalAccessError: io/netty/channel/VoidChannelPromise
        at io.vertx.core.net.impl.ConnectionBase.<init>(ConnectionBase.java:68) ~[my-vertx-project-1.0.jar:1.0]
        at io.vertx.core.net.impl.NetSocketImpl.<init>(NetSocketImpl.java:85) ~[my-vertx-project-1.0.jar:1.0]
        at io.vertx.core.net.impl.NetClientImpl.lambda$connected$8(NetClientImpl.java:239) ~[my-vertx-project-1.0.jar:1.0]
        at io.vertx.core.net.impl.VertxNetHandler.handlerAdded(VertxNetHandler.java:39) ~[my-vertx-project-1.0.jar:1.0]
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597) ~[my-vertx-project-1.0.jar:1.0]
        ... 19 more

**Comment by vietj** [comment]
can we get a newer version of Mauricio's driver ?

**Comment by vietj** [comment]
when I do dependency:tree with maven I get the vertx version, so I'm not sure what is the problem here

**Comment by connorliveraise** [comment]
@vietj The problem is that com.github.mauricio:db-async-common_2.12:0.2.21 has a hard dependency on netty 4.1.6, and I do not believe they have a newer version. There are several [pull](https://github.com/mauricio/postgresql-async/pull/224) [requests](https://github.com/mauricio/postgresql-async/pull/223) to update netty, but in the meantime if you could please update the pom here to exclude netty-all transitively, and include a newer version.

Sample gradle file to reproduce:
```
apply plugin: 'java'
repositories {
  jcenter()
 mavenCentral()
}
dependencies {
  compile ("io.vertx:vertx-mysql-postgresql-client:3.5.2") {
    //exclude group: 'io.netty', module: 'netty-all'
  }
}
```

gradle dep shows:

> compile - Dependencies for source set 'main'.
> \--- io.vertx:vertx-mysql-postgresql-client:3.5.2
>      +--- io.vertx:vertx-sql-common:3.5.2
>      +--- org.scala-lang:scala-library:2.12.4
>      +--- com.github.mauricio:postgresql-async_2.12:0.2.21
>      |    +--- org.scala-lang:scala-library:2.12.1 -> 2.12.4
>      |    \--- com.github.mauricio:db-async-common_2.12:0.2.21
>      |         +--- org.scala-lang:scala-library:2.12.1 -> 2.12.4
>      |         +--- joda-time:joda-time:2.9.7
>      |         +--- org.joda:joda-convert:1.8.1
>      |         +--- io.netty:netty-all:4.1.6.Final
>      |         \--- org.javassist:javassist:3.21.0-GA
>      \--- com.github.mauricio:mysql-async_2.12:0.2.21
>           +--- org.scala-lang:scala-library:2.12.1 -> 2.12.4
>           \--- com.github.mauricio:db-async-common_2.12:0.2.21 (*)
>

**Comment by vietj** [comment]
sure we can do that

**Comment by vietj** [comment]
actually exclusion already happens in master branch, can you have a check it works for you ?

**Comment by connorliveraise** [comment]
Interesting, I see it excluded in the pom on maven central too. I wonder why the it isn't working for gradle here.

I can get it working when I put the exclude in my gradle, so I'll close the issue.
