### ISSUE TITLE
3.0.0 release with adjusted Logging dependency

### ISSUE THREAD

**Issue by philrykoff** [vert-x3/vertx-mysql-postgresql-client#23]
Hi together,

thanks for wrapping up an async postgres client! 

Could you release a 3.0.0 version of this with adjusted Logging dependencies? The one currently available via the public maven repos (milestone6) is still linked to io.vertx.core.logging.impl.LoggerFactory, while there was a shift to io.vertx.core.logging.LoggerFactory with the final 3.0.0 vertx release.

I would be so grateful :-)

```
  <dependencies>
      <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-stack-depchain</artifactId>
            <version>3.0.0</version>
            <type>pom</type>
        </dependency>

        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-mysql-postgresql-client</artifactId>
            <version>3.0.0-milestone6</version>
        </dependency>

        <dependency>
            <groupId>joda-time</groupId>
            <artifactId>joda-time</artifactId>
            <version>2.8.2</version>
        </dependency>
        
        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-sql-common</artifactId>
            <version>3.0.0</version>
            <type>jar</type>
        </dependency>
  </dependencies>
```

The above POM throws 

```
java.lang.NoClassDefFoundError: io/vertx/core/logging/impl/LoggerFactory
	at io.vertx.ext.asyncsql.impl.BaseSQLClient$class.$init$(BaseSQLClient.scala:23)
	at io.vertx.ext.asyncsql.impl.PostgreSQLClient.<init>(PostgreSQLClient.scala:10)
	at io.vertx.ext.asyncsql.impl.AsyncSQLClientImpl.<init>(AsyncSQLClientImpl.scala:17)
	at io.vertx.ext.asyncsql.impl.ClientHolder.client(ClientHolder.java:47)
	at io.vertx.ext.asyncsql.impl.ClientWrapper.<init>(ClientWrapper.java:34)
	at io.vertx.ext.asyncsql.impl.ClientHelper.getOrCreate(ClientHelper.java:48)
	at io.vertx.ext.asyncsql.PostgreSQLClient.createShared(PostgreSQLClient.java:69)
	at utils.JdbcPooler.connectToDatabase(JdbcPooler.java:73)
	at utils.JdbcPooler.<init>(JdbcPooler.java:54)
	at utils.JdbcPooler.getInstance(JdbcPooler.java:65)
	at com.elements.hermes.MainVerticle.start(MainVerticle.java:48)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:111)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$169(DeploymentManager.java:407)
	at io.vertx.core.impl.DeploymentManager$$Lambda$30/2139715830.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$15(ContextImpl.java:314)
	at io.vertx.core.impl.ContextImpl$$Lambda$8/706895319.run(Unknown Source)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:357)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: io.vertx.core.logging.impl.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 20 more
```

**Comment by cescoffier** [comment]
This component was not part of the 3.0 release because of a concurrency issue. The "master" branch provides you an up to date version.

To get it, checkout the repository and compile it with:

    mvn clean install -DskipTests

(skip the tests because it requires configured MySQL and PostGres databases)

This component will be released in vert.x 3.1 that should be publicly available shortly.

**Comment by philrykoff** [comment]
thx
