### ISSUE TITLE
Error migrating to version 3.2.1

### ISSUE THREAD

**Issue by leosilvadev** [vert-x3/vertx-mysql-postgresql-client#39]
I have tried to change a vertx-jdbc for vertx-mysql-postgresql-client implementation (version 3.2.1) in Groovy, but I got:
`java.lang.NoSuchMethodError: io.vertx.core.Future.setHandler(Lio/vertx/core/Handler;)Lio/vertx/core/Future;`

So I just downgraded to the version 3.2.0 and it is working fine... can someone help me with this issue?

The full stacktrace:

> java.lang.NoSuchMethodError: io.vertx.core.Future.setHandler(Lio/vertx/core/Handler;)Lio/vertx/core/Future;
	at io.vertx.ext.asyncsql.impl.AsyncSQLConnectionImpl.lambda$query$9(AsyncSQLConnectionImpl.java:110)
	at io.vertx.ext.asyncsql.impl.AsyncSQLConnectionImpl$$Lambda$19/1842876050.handle(Unknown Source)
	at io.vertx.ext.asyncsql.impl.AsyncSQLConnectionImpl.beginTransactionIfNeeded(AsyncSQLConnectionImpl.java:240)
	at io.vertx.ext.asyncsql.impl.AsyncSQLConnectionImpl.query(AsyncSQLConnectionImpl.java:108)
	at io.vertx.groovy.ext.sql.SQLConnection.query(SQLConnection.groovy:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:187)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:68)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
	at com.pismo.mysql.handlers.MysqlEventsHandler.select(MysqlEventsHandler.groovy:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:151)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:179)
	at com.pismo.mysql.handlers.MysqlEventsHandler.handleSingleOperation(MysqlEventsHandler.groovy:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:382)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:151)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at com.pismo.mysql.handlers.MysqlEventsHandler$_registerConsumers_closure1$_closure7.doCall(MysqlEventsHandler.groovy:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at groovy.lang.Closure.call(Closure.java:423)
	at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:51)
	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:103)
	at com.sun.proxy.$Proxy4.handle(Unknown Source)
	at io.vertx.groovy.ext.asyncsql.AsyncSQLClient$1.handle(AsyncSQLClient.groovy:65)
	at io.vertx.groovy.ext.asyncsql.AsyncSQLClient$1.handle(AsyncSQLClient.groovy)
	at io.vertx.ext.asyncsql.impl.BaseSQLClient.lambda$getConnection$2(BaseSQLClient.java:67)
	at io.vertx.ext.asyncsql.impl.BaseSQLClient$$Lambda$15/1778559657.handle(Unknown Source)
	at io.vertx.ext.asyncsql.impl.ScalaUtils$3.apply(ScalaUtils.java:81)
	at io.vertx.ext.asyncsql.impl.ScalaUtils$3.apply(ScalaUtils.java:77)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at io.vertx.ext.asyncsql.impl.VertxEventLoopExecutionContext.lambda$execute$5(VertxEventLoopExecutionContext.java:70)
	at io.vertx.ext.asyncsql.impl.VertxEventLoopExecutionContext$$Lambda$18/1624667339.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$16(ContextImpl.java:335)
	at io.vertx.core.impl.ContextImpl$$Lambda$7/915416632.run(Unknown Source)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:357)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at java.lang.Thread.run(Thread.java:745)

**Comment by pmlopes** [comment]
Did you rebuild your code against 3.2.1? Did you update the remaining components to 3.2.1 or just async mysql postgres client?

**Comment by leosilvadev** [comment]
I just updated the version of the async-mysql-pg-client and the vertx to the newest version

**Comment by pmlopes** [comment]
@leosilvadev can you please provide a reproducer example

**Comment by leosilvadev** [comment]
Sure, I'm using Java8, and my dependencies are:

`dependencies {
	compile 'org.codehaus.groovy:groovy-all:2.4.3'
	compile("io.vertx:vertx-lang-groovy:3.2.0"){
		exclude group: 'org.codehaus.groovy', module: 'groovy-all'
	}
	compile 'io.vertx:vertx-mysql-postgresql-client:3.2.1'
	
	compile 'com.bloidonia:groovy-stream:0.9.0'
	compile 'org.slf4j:slf4j-log4j12:1.7.14'

	testCompile group: 'junit', name: 'junit', version: '4.+'
	testCompile 'org.spockframework:spock-core:1.0-groovy-2.4'
}`


The code:
`static main(args){
		Vertx vertx = Vertx.vertx()
		
		def config = [
			host: Env.mysqlHost(),
			port: Env.mysqlPort(),
			username: Env.mysqlUser(),
			password: Env.mysqlPass(),
			database: Env.mysqlDatabase(),
			maxPoolSize: Env.mysqlPoolSize()
		]
		AsyncSQLClient client = MySQLClient.createShared(vertx, config)
		client.getConnection({
			SQLConnection connection = it.result()
			connection.query("select * from Cards", { res ->
				println res.result()
			})
		})
	}`

**Comment by pmlopes** [comment]
I think the issue is because your groovy dependency is still 3.2.0 and the rest 3.2.1, i think it should be:

```
dependencies {

    compile "org.codehaus.groovy:groovy-all:2.4.3"
    compile("io.vertx:vertx-lang-groovy:3.2.1"){
        exclude group: "org.codehaus.groovy', module: "groovy-all"
    }
    compile "io.vertx:vertx-mysql-postgresql-client:3.2.1"

    compile "com.bloidonia:groovy-stream:0.9.0"
    compile "org.slf4j:slf4j-log4j12:1.7.14"

    testCompile group: "junit", name: "junit", version: "4.+"
    testCompile "org.spockframework:spock-core:1.0-groovy-2.4"
}
```

**Comment by leosilvadev** [comment]
@pmlopes that's it, thanks for the help!

**Comment by devicharan** [comment]
I had the same issue and i use java 8. Downgraded to 3.2.0 and it started working..
