### ISSUE TITLE
java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory

### ISSUE THREAD

**Issue by GuillaumeUnice** [vert-x3/vertx-mysql-postgresql-client#71]
Hi I try to use postgresqlClient,
I start a Postgres with the official docker image:
`
docker run --name postgres -p 5432:5432 -d postgres
`

this is my Verticle
```
public class WorkerVerticle extends AbstractVerticle {

    @Override
    public void start(Future<Void> future) {
        RedisClient redis = RedisClient.create(vertx, new RedisOptions().setHost("127.0.0.1"));

      JsonObject postgreSQLClientConfig = new JsonObject().put("host", "localhost");

        AsyncSQLClient postgreSQLClient = PostgreSQLClient.createShared(vertx, postgreSQLClientConfig);

        postgreSQLClient.getConnection(res -> {
            if (res.succeeded()) {
                SQLConnection connection = res.result();

                System.out.println("RESULT null");
            } else {
                System.out.println("Connection or Operation Failed " + res.cause());
            }
        });
}
```

And I have the following error:
```
mars 29, 2017 12:29:37 PM io.vertx.ext.asyncsql.impl.pool.AsyncConnectionPool
INFOS: creating a connection went wrong
java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at com.github.mauricio.async.db.util.Log$.getByName(Log.scala:27)
	at com.github.mauricio.async.db.postgresql.column.PostgreSQLIntervalEncoderDecoder$.<init>(PostgreSQLIntervalEncoderDecoder.scala:28)
	at com.github.mauricio.async.db.postgresql.column.PostgreSQLIntervalEncoderDecoder$.<clinit>(PostgreSQLIntervalEncoderDecoder.scala)
	at com.github.mauricio.async.db.postgresql.column.PostgreSQLColumnEncoderRegistry.<init>(PostgreSQLColumnEncoderRegistry.scala:65)
	at com.github.mauricio.async.db.postgresql.column.PostgreSQLColumnEncoderRegistry$.<init>(PostgreSQLColumnEncoderRegistry.scala:28)
	at com.github.mauricio.async.db.postgresql.column.PostgreSQLColumnEncoderRegistry$.<clinit>(PostgreSQLColumnEncoderRegistry.scala)
	at com.github.mauricio.async.db.postgresql.column.PostgreSQLColumnEncoderRegistry.Instance(PostgreSQLColumnEncoderRegistry.scala)
	at io.vertx.ext.asyncsql.impl.pool.PostgresqlAsyncConnectionPool.create(PostgresqlAsyncConnectionPool.java:42)
	at io.vertx.ext.asyncsql.impl.pool.AsyncConnectionPool.createConnection(AsyncConnectionPool.java:61)
	at io.vertx.ext.asyncsql.impl.pool.AsyncConnectionPool.createOrWaitForAvailableConnection(AsyncConnectionPool.java:77)
	at io.vertx.ext.asyncsql.impl.pool.AsyncConnectionPool.take(AsyncConnectionPool.java:86)
	at io.vertx.ext.asyncsql.impl.BaseSQLClient.getConnection(BaseSQLClient.java:66)
	at io.vertx.ext.asyncsql.impl.AsyncSQLClientImpl.getConnection(AsyncSQLClientImpl.java:53)
	at io.vertx.ext.asyncsql.impl.ClientWrapper.getConnection(ClientWrapper.java:51)
	at fr.treeptik.vertx.worker.WorkerVerticle.start(WorkerVerticle.java:62)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:434)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 21 more
```

Do you think it's just a dependency problem log4j?

**Comment by vietj** [comment]
yes because of https://github.com/vert-x3/vertx-mysql-postgresql-client/blob/master/pom.xml#L38

we should make it non provided like we have done for Vert.x Auth Shiro but with the same version than Vert.x uses (non forcibly)

**Comment by tsegismont** [comment]
slf4j has provided scope in in the module POM. You must add it to your own
POM.

2017-03-29 12:37 GMT+02:00 GuillaumeUnice <notifications@github.com>:

**Comment by GuillaumeUnice** [comment]
Indeed, now I just have a connection issue

```
mars 29, 2017 12:47:53 PM io.vertx.ext.asyncsql.impl.PostgreSQLClientImpl
INFOS: Creating configuration for localhost:5432
703 [vert.x-eventloop-thread-2] ERROR com.github.mauricio.async.db.postgresql.PostgreSQLConnection - Error with message -> ErrorMessage(fields=Map(Line -> 502, File -> miscinit.c, SQLSTATE -> 28000, Routine -> InitializeSessionUserId, V -> FATAL, Message -> role "vertx" does not exist, Severity -> FATAL))
704 [vert.x-eventloop-thread-2] ERROR com.github.mauricio.async.db.postgresql.PostgreSQLConnection - Error on connection
com.github.mauricio.async.db.postgresql.exceptions.GenericDatabaseException: ErrorMessage(fields=Map(Line -> 502, File -> miscinit.c, SQLSTATE -> 28000, Routine -> InitializeSessionUserId, V -> FATAL, Message -> role "vertx" does not exist, Severity -> FATAL))
	at com.github.mauricio.async.db.postgresql.PostgreSQLConnection.onError(PostgreSQLConnection.scala:175)
	at com.github.mauricio.async.db.postgresql.codec.PostgreSQLConnectionHandler.channelRead0(PostgreSQLConnectionHandler.scala:206)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)

```
