### ISSUE TITLE
MySQL TIME columns don't work

### ISSUE THREAD

**Issue by mslenc** [vert-x3/vertx-mysql-postgresql-client#92]
The stack trace is:
```
Caused by: java.lang.IllegalStateException: Illegal type in JsonObject: class scala.concurrent.duration.FiniteDuration
	at io.vertx.core.json.Json.checkAndCopy(Json.java:215)
	at io.vertx.core.json.JsonArray.add(JsonArray.java:444)
	at io.vertx.ext.asyncsql.impl.ScalaUtils.convertValue(ScalaUtils.java:138)
```

**Comment by vietj** [comment]
can you provide a reproducer test ?

**Comment by mslenc** [comment]
As far as I can tell, this will reproduce the problem:
1. Create a table with a TIME column
2. Put some data in that column
3. Try to query for it..

**Comment by Narigo** [comment]
I could create a reproducer for this problem.
In PostgreSQL, `TIME` returns `org.joda.time.LocalTime`, in MySQL it returns `scala.concurrent.duration.FiniteDuration`.

What kind of return value would you expect?
For MySQL / `FiniteDuration` I'd go for a number in milliseconds and `LocalTime` I'd return as String (`HH:MM:SS.<milliseconds>`). There is a difference between PostgreSQL and MySQL regarding the column type `TIME`, so I think it might make sense to reflect that in the return value as well.

**Comment by mslenc** [comment]
Yeah, MySQL's TIME is somewhat ambiguous in meaning, and can be used [for both](https://dev.mysql.com/doc/refman/5.7/en/time.html) durations and times.. But still, I wouldn't encode them differently, that it becomes a FiniteDuration seems more of an implementation artifact than anything else.. `HH:MM:SS` will both match what the database itself is returning and the PostgreSQL version..

**Comment by Narigo** [comment]
Ok, then I'll make it return "HH:MM:SS.<ms>" in all cases.

**Comment by kirillkh** [comment]
Is there any workaround for this problem?

**Comment by tsegismont** [comment]
@kirillkh you could update your queries to convert the time column with `TO_CHAR`, then in the verticle retrieve the time as a `String`

**Comment by kirillkh** [comment]
What worked for me: TABLE.TIME.cast(String.class)
