### ISSUE TITLE
use vertx-mysql-postgresql-client-3.4.1 query MySQL 5.7.8(or later) Json Data failed

### ISSUE THREAD

**Issue by ordiychen** [vert-x3/vertx-mysql-postgresql-client#97]
I use vertx-mysql-client query data from **mySQL5.7.8**,have an error 
my dependency :    
`
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-mysql-postgresql-client</artifactId>
  <version>3.4.1</version>
</dependency>
`
error log:   
`
2017-12-21 14:45:23.153 [vert.x-eventloop-thread-5] ERROR c.g.m.a.d.m.MySQLConnection:119- Transport failure 
scala.MatchError: 245 (of class java.lang.Integer)
	at com.github.mauricio.async.db.mysql.codec.DecoderRegistry.binaryDecoderFor(DecoderRegistry.scala:37)
	at com.github.mauricio.async.db.mysql.decoder.ColumnDefinitionDecoder.decode(ColumnDefinitionDecoder.scala:63)
	at com.github.mauricio.async.db.mysql.codec.MySQLFrameDecoder.decodeQueryResult(MySQLFrameDecoder.scala:234)
	at com.github.mauricio.async.db.mysql.codec.MySQLFrameDecoder.doDecoding(MySQLFrameDecoder.scala:163)
	at com.github.mauricio.async.db.mysql.codec.MySQLFrameDecoder.handleCommonFlow(MySQLFrameDecoder.scala:157)
	at com.github.mauricio.async.db.mysql.codec.MySQLFrameDecoder.decode(MySQLFrameDecoder.scala:90)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
2017-12-21 14:45:23.155 [vert.x-eventloop-thread-3] ERROR c.j.d.p.c.GetPermissionInfoHandler:53- get_permission_info failed,causeL:
`

**MySQL tables desc info:**  

| Field           | Type            | Null | Key | Default           | Extra          |
--- | --- | --- | --- | --- | --- |
| id              | int(11)         | NO   | PRI | NULL              | auto_increment |  
| dev_id          | int(11)         | NO   | MUL | NULL              |                |  
| dev_key         | varchar(64)     | NO   | MUL | NULL              |                |  
| api_key         | varchar(64)     | NO   |     | NULL              |                |  
| start_time      | timestamp       | YES  |     | CURRENT_TIMESTAMP |                |  
| end_time        | timestamp       | YES  |     | CURRENT_TIMESTAMP |                |   
| total_times     | int(11)         | YES  |     | NULL              |                |   
| frequency_times | int(11)         | YES  |     | NULL              |                |   
| frequency_unit  | int(11)         | YES  |     | NULL              |                |   
| extras          | json            | YES  |     | NULL              |                |   

I want to try to Solve this problem,but my Scale program is bad.

**Comment by ordiychen** [comment]
but I use [vertx-jdbc-client](http://vertx.io/docs/vertx-jdbc-client/java/) slove this error.

**Comment by juanavelez** [comment]
This might not be the actual cause of the error but it seems strange you close the connection BEFORE you read the results. Have you tried closing the connection AFTER you have read the results?

**Comment by iheng-scau** [comment]
if getting rid of the json columns, the exception never be raised.  It seems that the problem lays on this client does not support json column query.

**Comment by andy-yx-chen** [comment]
it is! mauricio is buggy, and not longer supported, try https://github.com/andy-yx-chen/vertx-mysql-postgresql-client this one and if it still fails, try to contact jasync-sql project and ask them to fix the bug
